package lab.pkg5_alessandroreyes;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Dell
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        SpinnerNumberModel YY = new SpinnerNumberModel();
        YY.setMaximum(10);
        YY.setMinimum(1);
        YY.setValue(1);
        js_pod.setModel(YY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_stanlee = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        btn_especial = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        m_superheroe = new javax.swing.JMenu();
        jmi_crearS = new javax.swing.JMenuItem();
        jmi_listarS = new javax.swing.JMenuItem();
        jm_villano = new javax.swing.JMenu();
        jmi_crearV = new javax.swing.JMenuItem();
        jmi_listarV = new javax.swing.JMenuItem();
        jmi_csuperpoder = new javax.swing.JMenuItem();
        jmi_listanos = new javax.swing.JMenuItem();
        jmi_listanov = new javax.swing.JMenuItem();
        jmi_atrapar = new javax.swing.JMenuItem();
        jmi_escape = new javax.swing.JMenuItem();
        jmi_encarcelados = new javax.swing.JMenuItem();
        jd_nosuper = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_nosuper = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jd_novillano = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_novillano = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jd_crearSV = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_Cnom_ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_Cedad_ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_Corigen_ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_Caltura_ = new javax.swing.JTextField();
        lab_s = new javax.swing.JLabel();
        tf_Cnum_ = new javax.swing.JTextField();
        lab_v = new javax.swing.JLabel();
        btn_crear_r_ = new javax.swing.JButton();
        btn_crear_ = new javax.swing.JButton();
        jd_crearSP = new javax.swing.JDialog();
        btn_CrearSP_r_ = new javax.swing.JButton();
        btn_CrearSP_ = new javax.swing.JButton();
        js_pod = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_SPdesc_ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rb_msi_ = new javax.swing.JRadioButton();
        rb_mno_ = new javax.swing.JRadioButton();
        bg_mortal = new javax.swing.ButtonGroup();
        jd_listaSV = new javax.swing.JDialog();
        lab_Sgrupo = new javax.swing.JLabel();
        lab_Vgrupo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_listaSV = new javax.swing.JList<>();
        btn_listavs_r_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pf_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_arbol);

        btn_especial.setText("Boton especial");

        jMenu1.setText("Acciones");

        m_superheroe.setText("Superheroe");

        jmi_crearS.setText("Crear");
        jmi_crearS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearSActionPerformed(evt);
            }
        });
        m_superheroe.add(jmi_crearS);

        jmi_listarS.setText("Listar");
        jmi_listarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarSActionPerformed(evt);
            }
        });
        m_superheroe.add(jmi_listarS);

        jMenu1.add(m_superheroe);

        jm_villano.setText("Villano");

        jmi_crearV.setText("Crear");
        jmi_crearV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearVActionPerformed(evt);
            }
        });
        jm_villano.add(jmi_crearV);

        jmi_listarV.setText("Listar");
        jmi_listarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarVActionPerformed(evt);
            }
        });
        jm_villano.add(jmi_listarV);

        jMenu1.add(jm_villano);

        jmi_csuperpoder.setText("Crear superpoder");
        jmi_csuperpoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_csuperpoderActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_csuperpoder);

        jmi_listanos.setText("Lista superheroe sin grupo");
        jMenu1.add(jmi_listanos);

        jmi_listanov.setText("Lista de villanos sin grupo");
        jMenu1.add(jmi_listanov);

        jmi_atrapar.setText("Atrapar Villano");
        jMenu1.add(jmi_atrapar);

        jmi_escape.setText("Escaparse de la carcel");
        jMenu1.add(jmi_escape);

        jmi_encarcelados.setText("Encarcelados");
        jMenu1.add(jmi_encarcelados);

        jMenuBar1.add(jMenu1);

        jd_stanlee.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_stanleeLayout = new javax.swing.GroupLayout(jd_stanlee.getContentPane());
        jd_stanlee.getContentPane().setLayout(jd_stanleeLayout);
        jd_stanleeLayout.setHorizontalGroup(
            jd_stanleeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_stanleeLayout.createSequentialGroup()
                .addGroup(jd_stanleeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_stanleeLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_stanleeLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btn_especial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jd_stanleeLayout.setVerticalGroup(
            jd_stanleeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_stanleeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_especial, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jl_nosuper.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_nosuper);

        jLabel4.setText("Superheroes sin grupo");

        jButton1.setText("Regresar");

        jButton2.setText("agregar a un grupo");

        jButton3.setText("Agregar superpoder ");

        javax.swing.GroupLayout jd_nosuperLayout = new javax.swing.GroupLayout(jd_nosuper.getContentPane());
        jd_nosuper.getContentPane().setLayout(jd_nosuperLayout);
        jd_nosuperLayout.setHorizontalGroup(
            jd_nosuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nosuperLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(254, 254, 254)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(jd_nosuperLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jd_nosuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_nosuperLayout.setVerticalGroup(
            jd_nosuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nosuperLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jd_nosuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        jl_novillano.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_novillano);

        jLabel5.setText("Villanos sin grupo");

        jButton4.setText("Regresar");

        jButton5.setText("Agregar a un grupo");

        jButton6.setText("Darle superpoderes");

        javax.swing.GroupLayout jd_novillanoLayout = new javax.swing.GroupLayout(jd_novillano.getContentPane());
        jd_novillano.getContentPane().setLayout(jd_novillanoLayout);
        jd_novillanoLayout.setHorizontalGroup(
            jd_novillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_novillanoLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jd_novillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_novillanoLayout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(276, 276, 276)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton6))
        );
        jd_novillanoLayout.setVerticalGroup(
            jd_novillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_novillanoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jd_novillanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)))
        );

        jLabel6.setText("Nombre ");

        jLabel7.setText("Edad");

        jLabel8.setText("Planeta de origen");

        jLabel9.setText("Altura");

        lab_s.setText("Numero de villano atrapados");

        lab_v.setText("Numero de muertes causadas");

        btn_crear_r_.setText("Regresar");
        btn_crear_r_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crear_r_MouseClicked(evt);
            }
        });

        btn_crear_.setText("crear");
        btn_crear_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crear_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearSVLayout = new javax.swing.GroupLayout(jd_crearSV.getContentPane());
        jd_crearSV.getContentPane().setLayout(jd_crearSVLayout);
        jd_crearSVLayout.setHorizontalGroup(
            jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSVLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearSVLayout.createSequentialGroup()
                        .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(400, 400, 400)
                        .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_v)
                            .addComponent(lab_s)
                            .addComponent(jLabel9))
                        .addContainerGap(184, Short.MAX_VALUE))
                    .addGroup(jd_crearSVLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSVLayout.createSequentialGroup()
                        .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_Corigen_, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Cedad_, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Cnom_))
                        .addGap(150, 150, 150)
                        .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Caltura_, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Cnum_, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
            .addGroup(jd_crearSVLayout.createSequentialGroup()
                .addComponent(btn_crear_r_)
                .addGap(264, 264, 264)
                .addComponent(btn_crear_, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_crearSVLayout.setVerticalGroup(
            jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSVLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lab_v)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lab_s))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Cnom_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Cnum_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Cedad_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Caltura_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Corigen_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(jd_crearSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear_r_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crear_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btn_CrearSP_r_.setText("Regresar");
        btn_CrearSP_r_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearSP_r_MouseClicked(evt);
            }
        });

        btn_CrearSP_.setText("Crear");
        btn_CrearSP_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CrearSP_MouseClicked(evt);
            }
        });

        jLabel10.setText("Nivel de poder");

        jLabel11.setText("Descripcion");

        jLabel12.setText("Superpoder mortal?");

        bg_mortal.add(rb_msi_);
        rb_msi_.setText("Si");

        bg_mortal.add(rb_mno_);
        rb_mno_.setText("No");

        javax.swing.GroupLayout jd_crearSPLayout = new javax.swing.GroupLayout(jd_crearSP.getContentPane());
        jd_crearSP.getContentPane().setLayout(jd_crearSPLayout);
        jd_crearSPLayout.setHorizontalGroup(
            jd_crearSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSPLayout.createSequentialGroup()
                .addComponent(btn_CrearSP_r_)
                .addGap(285, 285, 285)
                .addComponent(btn_CrearSP_, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_crearSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearSPLayout.createSequentialGroup()
                        .addComponent(rb_msi_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_mno_))
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(js_pod, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(431, 431, 431))
            .addGroup(jd_crearSPLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(tf_SPdesc_, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jd_crearSPLayout.setVerticalGroup(
            jd_crearSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSPLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_pod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_SPdesc_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_msi_)
                    .addComponent(rb_mno_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addGroup(jd_crearSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CrearSP_r_, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CrearSP_, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lab_Sgrupo.setText("Lista de superheroes ya en su grupo");

        lab_Vgrupo.setText("Lista de villanos ya en su grupo");

        jl_listaSV.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_listaSV);

        btn_listavs_r_.setText("Regresar");
        btn_listavs_r_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listavs_r_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listaSVLayout = new javax.swing.GroupLayout(jd_listaSV.getContentPane());
        jd_listaSV.getContentPane().setLayout(jd_listaSVLayout);
        jd_listaSVLayout.setHorizontalGroup(
            jd_listaSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaSVLayout.createSequentialGroup()
                .addGroup(jd_listaSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listaSVLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(jd_listaSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_Vgrupo)
                            .addComponent(lab_Sgrupo)))
                    .addGroup(jd_listaSVLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_listavs_r_))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jd_listaSVLayout.setVerticalGroup(
            jd_listaSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaSVLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lab_Sgrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_Vgrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_listavs_r_))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido Stan Lee");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        btn_login.setText("Log in");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        if (tf_user.getText().equals("stanlee") && pf_pass.getText().equals("spiderman99")) {
            this.setVisible(false);
            jd_stanlee.setModal(true);
            jd_stanlee.pack();
            jd_stanlee.setLocationRelativeTo(this);
            jd_stanlee.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta.");
            tf_user.setText("");
            pf_pass.setText("");
        }
            
    }//GEN-LAST:event_btn_loginMouseClicked

    private void jmi_crearSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearSActionPerformed
        jd_stanlee.setModal(false);
        jd_stanlee.setVisible(false);
        jd_crearSV.setModal(true);
        jd_crearSV.pack();
        jd_crearSV.setLocationRelativeTo(this);
        jd_crearSV.setVisible(true);
        lab_s.setVisible(true);
        lab_v.setVisible(false);
        
    }//GEN-LAST:event_jmi_crearSActionPerformed

    private void jmi_crearVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearVActionPerformed
        jd_stanlee.setModal(false);
        jd_stanlee.setVisible(false);
        jd_crearSV.setModal(true);
        jd_crearSV.pack();
        jd_crearSV.setLocationRelativeTo(this);
        jd_crearSV.setVisible(true);
        lab_s.setVisible(false);
        lab_v.setVisible(true);
    }//GEN-LAST:event_jmi_crearVActionPerformed

    private void btn_crear_r_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crear_r_MouseClicked
        jd_crearSV.setModal(false);
        jd_crearSV.setVisible(false);
        jd_stanlee.setModal(true);
        jd_stanlee.pack();
        jd_stanlee.setLocationRelativeTo(this);
        jd_stanlee.setVisible(true);
        tf_Caltura_.setText("");
        tf_Cedad_.setText("");
        tf_Cnom_.setText("");
        tf_Cnum_.setText("");
        tf_Corigen_.setText("");
    }//GEN-LAST:event_btn_crear_r_MouseClicked

    private void btn_crear_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crear_MouseClicked
        if(lab_s.isVisible()){
            heroes.add(new Superheroe(tf_Cnom_.getText(), tf_Corigen_.getText(), Integer.parseInt(tf_Cedad_.getText()),
                    Integer.parseInt(tf_Caltura_.getText()), Integer.parseInt(tf_Cnum_.getText())));
            JOptionPane.showMessageDialog(jd_crearSV, "Superheroe creador con exito.");
            tf_Caltura_.setText("");
            tf_Cedad_.setText("");
            tf_Cnom_.setText("");
            tf_Cnum_.setText("");
            tf_Corigen_.setText("");
            
        }else{
            villanos.add(new Villano(tf_Cnom_.getText(), tf_Corigen_.getText(), Integer.parseInt(tf_Cedad_.getText()),
                    Integer.parseInt(tf_Caltura_.getText()), Integer.parseInt(tf_Cnum_.getText()),false));
            JOptionPane.showMessageDialog(jd_crearSV, "Villano creador con exito.");
            tf_Caltura_.setText("");
            tf_Cedad_.setText("");
            tf_Cnom_.setText("");
            tf_Cnum_.setText("");
            tf_Corigen_.setText("");
        }
    }//GEN-LAST:event_btn_crear_MouseClicked

    private void jmi_csuperpoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_csuperpoderActionPerformed
        jd_stanlee.setModal(false);
        jd_stanlee.setVisible(false);
        jd_crearSP.setModal(true);
        jd_crearSP.pack();
        jd_crearSP.setLocationRelativeTo(this);
        jd_crearSP.setVisible(true);
    }//GEN-LAST:event_jmi_csuperpoderActionPerformed

    private void btn_CrearSP_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearSP_MouseClicked
        if(rb_msi_.isSelected()){
            poderes.add(new Superpoder(js_pod.getComponentCount(), true, tf_SPdesc_.getText()));
            JOptionPane.showMessageDialog(jd_crearSP, "Superpoder creado con exito.");
            tf_SPdesc_.setText("");
            js_pod.setValue(1);
            rb_mno_.setSelected(true);
        }else{
            poderes.add(new Superpoder(js_pod.getComponentCount(), true, tf_SPdesc_.getText()));
            JOptionPane.showMessageDialog(jd_crearSP, "Superpoder creado con exito.");
            tf_SPdesc_.setText("");
            js_pod.setValue(1);
            rb_mno_.setSelected(true);
        }
        
    }//GEN-LAST:event_btn_CrearSP_MouseClicked

    private void btn_CrearSP_r_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CrearSP_r_MouseClicked
        jd_crearSP.setModal(false);
        jd_crearSP.setVisible(false);
        jd_stanlee.setModal(true);
        jd_stanlee.pack();
        jd_stanlee.setLocationRelativeTo(this);
        jd_stanlee.setVisible(true);
        tf_SPdesc_.setText("");
        js_pod.setValue(1);
        rb_mno_.setSelected(true);
    }//GEN-LAST:event_btn_CrearSP_r_MouseClicked

    private void jmi_listarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarSActionPerformed
        jd_stanlee.setModal(false);
        jd_stanlee.setVisible(false);
        jd_listaSV.setModal(true);
        jd_listaSV.pack();
        jd_listaSV.setLocationRelativeTo(this);
        jd_listaSV.setVisible(true);
        
        lab_Vgrupo.setVisible(false);
        lab_Sgrupo.setVisible(true);
        
        DefaultListModel m = (DefaultListModel) jl_listaSV.getModel();
        for (int i = 0; i < vengadores.size(); i++) {
            m.addElement(vengadores.get(i).toString());
        }
        for (int i = 0; i < xmen.size(); i++) {
            m.addElement(xmen.get(i).toString());
        }
        jl_listaSV.setModel(m);
    }//GEN-LAST:event_jmi_listarSActionPerformed

    private void jmi_listarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarVActionPerformed
        jd_stanlee.setModal(false);
        jd_stanlee.setVisible(false);
        jd_listaSV.setModal(true);
        jd_listaSV.pack();
        jd_listaSV.setLocationRelativeTo(this);
        jd_listaSV.setVisible(true);
        
        lab_Vgrupo.setVisible(true);
        lab_Sgrupo.setVisible(false);
        
        DefaultListModel m = (DefaultListModel) jl_listaSV.getModel();
        for (int i = 0; i < darkavenger.size(); i++) {
            m.addElement(darkavenger.get(i).toString());
        }
        for (int i = 0; i < sinister.size(); i++) {
            m.addElement(sinister.get(i).toString());
        }
        jl_listaSV.setModel(m);
    }//GEN-LAST:event_jmi_listarVActionPerformed

    private void btn_listavs_r_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listavs_r_MouseClicked
        jd_listaSV.setModal(false);
        jd_listaSV.setVisible(false);
        jd_stanlee.setModal(true);
        jd_stanlee.pack();
        jd_stanlee.setLocationRelativeTo(this);
        jd_stanlee.setVisible(true);
        
        lab_Vgrupo.setVisible(false);
        lab_Sgrupo.setVisible(false);
        
        DefaultListModel m = (DefaultListModel) jl_listaSV.getModel();
        m.removeAllElements();
        jl_listaSV.setModel(m);
    }//GEN-LAST:event_btn_listavs_r_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_mortal;
    private javax.swing.JButton btn_CrearSP_;
    private javax.swing.JButton btn_CrearSP_r_;
    private javax.swing.JButton btn_crear_;
    private javax.swing.JButton btn_crear_r_;
    private javax.swing.JButton btn_especial;
    private javax.swing.JButton btn_listavs_r_;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_crearSP;
    private javax.swing.JDialog jd_crearSV;
    private javax.swing.JDialog jd_listaSV;
    private javax.swing.JDialog jd_nosuper;
    private javax.swing.JDialog jd_novillano;
    private javax.swing.JDialog jd_stanlee;
    private javax.swing.JList<String> jl_listaSV;
    private javax.swing.JList<String> jl_nosuper;
    private javax.swing.JList<String> jl_novillano;
    private javax.swing.JMenu jm_villano;
    private javax.swing.JMenuItem jmi_atrapar;
    private javax.swing.JMenuItem jmi_crearS;
    private javax.swing.JMenuItem jmi_crearV;
    private javax.swing.JMenuItem jmi_csuperpoder;
    private javax.swing.JMenuItem jmi_encarcelados;
    private javax.swing.JMenuItem jmi_escape;
    private javax.swing.JMenuItem jmi_listanos;
    private javax.swing.JMenuItem jmi_listanov;
    private javax.swing.JMenuItem jmi_listarS;
    private javax.swing.JMenuItem jmi_listarV;
    private javax.swing.JSpinner js_pod;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JLabel lab_Sgrupo;
    private javax.swing.JLabel lab_Vgrupo;
    private javax.swing.JLabel lab_s;
    private javax.swing.JLabel lab_v;
    private javax.swing.JMenu m_superheroe;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JRadioButton rb_mno_;
    private javax.swing.JRadioButton rb_msi_;
    private javax.swing.JTextField tf_Caltura_;
    private javax.swing.JTextField tf_Cedad_;
    private javax.swing.JTextField tf_Cnom_;
    private javax.swing.JTextField tf_Cnum_;
    private javax.swing.JTextField tf_Corigen_;
    private javax.swing.JTextField tf_SPdesc_;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    ArrayList<Superheroe> heroes = new ArrayList();
    ArrayList<Villano> villanos = new ArrayList();
    ArrayList<Vengador> vengadores = new ArrayList();
    ArrayList<XMen> xmen = new ArrayList();
    ArrayList<DarkAvenger> darkavenger = new ArrayList();
    ArrayList<SinisterSix> sinister = new ArrayList();
    ArrayList<Superpoder> poderes = new ArrayList();
}
